// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk36ytVSvm6PXWfgAoKElpij0WD7XytzU',
    appId: '1:491621337253:web:8e8fd683d53c7d2e88a54c',
    messagingSenderId: '491621337253',
    projectId: 'money-logger-224',
    authDomain: 'money-logger-224.firebaseapp.com',
    storageBucket: 'money-logger-224.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5YcRVbsoUuUHAhVGA9sHnO4lpJD0p0mw',
    appId: '1:491621337253:android:af96ae1703f6d88488a54c',
    messagingSenderId: '491621337253',
    projectId: 'money-logger-224',
    storageBucket: 'money-logger-224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqyk_78yOWbz_hqjuccxTMPdQjP4zLA-U',
    appId: '1:491621337253:ios:02f2bd419d7bee6f88a54c',
    messagingSenderId: '491621337253',
    projectId: 'money-logger-224',
    storageBucket: 'money-logger-224.appspot.com',
    iosBundleId: 'com.example.moneyLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqyk_78yOWbz_hqjuccxTMPdQjP4zLA-U',
    appId: '1:491621337253:ios:1a30eb85a36f3a9088a54c',
    messagingSenderId: '491621337253',
    projectId: 'money-logger-224',
    storageBucket: 'money-logger-224.appspot.com',
    iosBundleId: 'com.example.moneyLogger.RunnerTests',
  );
}
